### ISSUE TITLE
Return only "text" via selection

### ISSUE THREAD

**Issue by mdroidian** [RoamJS/query-builder#274]
Requested from Christian K. via [slack](https://roamresearch.slack.com/archives/C016N2B66JU/p1723195570990849?thread_ts=1715488475.463839&cid=C016N2B66JU)

### Use Case

- the user is querying blocks that include `text` and an arbitrary amount of `[[pages]]`, `#tags`, and `{{buttons}}` 
- the user wants to display only the `text`
- as the number and location of the undesired parts of the block are indeterminate, this can be difficult to achieve with with `node:node:/regex/`

### Proposed Solution

- add a new [Selection](https://github.com/RoamJS/query-builder/blob/main/docs/query-builder.md#selections) data type that returns only `text`
  - eg: it removes any `[[pages]]`, `#tags`, or `{{buttons}}`
- something like `node:node:text-only`

Unsure how we'd handle block references `((9EzwbaEJs))`, especially when they contain `[[pages]]`, `#tags`, or `{{buttons}}`

### Workaround

For now, users can remove the undesired parts in `embed` view via css:

```css
/* targeting query result table */
/* only from column titled "text" */

/* hide all [[links]] and #tags */
.roamjs-query-results-view td[data-column-title="text"] .rm-page-ref__brackets,
.roamjs-query-results-view td[data-column-title="text"] .rm-page-ref
{
    display:none;
}

/* hide checkboxes */
.roamjs-query-results-view td[data-column-title="text"] .check-container
{
    display:none;
}
```
